/**
 * This test class covers basically three scenarios.
 * 1) When a case is inserted and comments are inserted and a Published article is used- Positive scenario.
 * 2) When a case is inserted and comments are inserted and a Non-Published article is used- Positive scenario with no Articles.
 * 3) Test for exceptions by passing values which can throw null.
 * <p /><p />
 * @author Nagendra Singh
 */

@IsTest(SeeAllData=false)
private class CaseCreationLightningControllerTest_ACE {

	private static Id IdknowledgeArticle;

}